language: java

env:
  - SCALA_VERSION=2.11.7

os:
  - osx

install:
  - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > ./sbt && chmod 0755 ./sbt

script:
  - ./sbt "++$SCALA_VERSION" test

matrix:
  include:
    - env: SCALA_VERSION=2.11.7
      os: linux
      jdk: oraclejdk7
    - env: SCALA_VERSION=2.10.5
      os: linux
      jdk: oraclejdk8
