language: java

env:
  - SCALA_VERSION=2.11.8

os:
  - osx

install:
  - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > ./sbt && chmod 0755 ./sbt

script:
  - ./sbt "++$SCALA_VERSION" clean coverage test

after_success:
  - sbt coverageReport coveralls

matrix:
  include:
    - env: SCALA_VERSION=2.11.8
      os: linux
      jdk: oraclejdk8
