language: java

env:
  - SCALA_VERSION=2.11.8
  - PYTHONPATH="src/main/python:$PYTHONPATH"

os:
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3-pip  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3-nose ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install csound       ; fi
  - pip3 install -r requirements.txt

install:
  - curl -s https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt > ./sbt && chmod 0755 ./sbt

script:
  - ./sbt "++$SCALA_VERSION" clean coverage test && python3 -m nose -vv src/test/python/csoundpp

after_success:
  - sbt coverageReport coveralls

matrix:
  include:
    - env: SCALA_VERSION=2.11.8
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - python3-pip
            - python3-nose
            - csound
